// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_MOBILE PhoneType = 0
	PhoneType_HOME   PhoneType = 1
	PhoneType_WORK   PhoneType = 2
)

var PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

type Person struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones               []*PhoneNumber       `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetPhones() []*PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Person) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

// Our address book file is just one of these.
type AddressBook struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddressBook) Reset()         { *m = AddressBook{} }
func (m *AddressBook) String() string { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()    {}
func (*AddressBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *AddressBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressBook.Unmarshal(m, b)
}
func (m *AddressBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressBook.Marshal(b, m, deterministic)
}
func (m *AddressBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressBook.Merge(m, src)
}
func (m *AddressBook) XXX_Size() int {
	return xxx_messageInfo_AddressBook.Size(m)
}
func (m *AddressBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressBook.DiscardUnknown(m)
}

var xxx_messageInfo_AddressBook proto.InternalMessageInfo

func (m *AddressBook) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type PhoneNumber struct {
	Number               string    `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=example.PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *PhoneNumber) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_MOBILE
}

func init() {
	proto.RegisterEnum("example.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Person)(nil), "example.Person")
	proto.RegisterType((*AddressBook)(nil), "example.AddressBook")
	proto.RegisterType((*PhoneNumber)(nil), "example.PhoneNumber")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0xa4, 0x69, 0x3e, 0x7b, 0x23, 0xb5, 0x5c, 0xaa, 0x84, 0x6e, 0x0c, 0x5d, 0x68,
	0x50, 0x49, 0xa1, 0x82, 0x3b, 0x17, 0x16, 0x0a, 0x8a, 0xd6, 0x96, 0xa1, 0xe2, 0x52, 0x52, 0x72,
	0xad, 0xc1, 0x4c, 0x66, 0xc8, 0x4c, 0xc1, 0x3e, 0x95, 0xaf, 0x28, 0x99, 0x4c, 0xfd, 0xb3, 0x9a,
	0x73, 0xce, 0x1c, 0xb8, 0xbf, 0x03, 0x87, 0xf4, 0x91, 0x72, 0x59, 0xd0, 0xc8, 0xbe, 0x89, 0xac,
	0x84, 0x16, 0xf8, 0xdf, 0xda, 0xc1, 0xf1, 0x5a, 0x88, 0x75, 0x41, 0x23, 0x13, 0xaf, 0x36, 0xaf,
	0x23, 0x9d, 0x73, 0x52, 0x3a, 0xe5, 0xb2, 0x69, 0x0e, 0x3f, 0x1d, 0xf0, 0x17, 0x54, 0x29, 0x51,
	0x22, 0x82, 0x57, 0xa6, 0x9c, 0x42, 0x27, 0x72, 0xe2, 0x0e, 0x33, 0x1a, 0xbb, 0xe0, 0xe6, 0x59,
	0xe8, 0x46, 0x4e, 0xdc, 0x66, 0x6e, 0x9e, 0x61, 0x1f, 0xda, 0xc4, 0xd3, 0xbc, 0x08, 0x5b, 0xa6,
	0xd4, 0x18, 0xbc, 0x00, 0x5f, 0xbe, 0x89, 0x92, 0x54, 0xe8, 0x45, 0xad, 0x38, 0x18, 0xf7, 0x93,
	0x1d, 0xce, 0xa2, 0x8e, 0x1f, 0x37, 0x7c, 0x45, 0x15, 0xb3, 0x1d, 0xbc, 0x86, 0xfd, 0x22, 0x55,
	0xfa, 0x65, 0x23, 0xb3, 0x54, 0x53, 0x16, 0xb6, 0x23, 0x27, 0x0e, 0xc6, 0x83, 0xa4, 0x41, 0x4d,
	0x76, 0xa8, 0xc9, 0x72, 0x87, 0xca, 0x82, 0xba, 0xff, 0xd4, 0xd4, 0x87, 0x57, 0x10, 0xdc, 0x64,
	0x59, 0x45, 0x4a, 0x4d, 0x84, 0x78, 0xc7, 0x53, 0xf0, 0x25, 0x09, 0x59, 0xd4, 0xdc, 0xf5, 0xed,
	0x83, 0x9f, 0xdb, 0x66, 0x16, 0xb3, 0xdf, 0xc3, 0x19, 0x04, 0xbf, 0x68, 0xf0, 0x08, 0xfc, 0xd2,
	0x28, 0xbb, 0xd7, 0x3a, 0x3c, 0x01, 0x4f, 0x6f, 0x25, 0x99, 0xcd, 0xdd, 0x31, 0xfe, 0x5d, 0xb2,
	0xdc, 0x4a, 0x62, 0xe6, 0xff, 0xec, 0x1c, 0x3a, 0xdf, 0x11, 0x02, 0xf8, 0xb3, 0xf9, 0xe4, 0xee,
	0x61, 0xda, 0xfb, 0x87, 0x7b, 0xe0, 0xdd, 0xce, 0x67, 0xd3, 0x9e, 0x53, 0xab, 0xe7, 0x39, 0xbb,
	0xef, 0xb9, 0x2b, 0xdf, 0x8c, 0xba, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x35, 0x6b, 0xe6, 0x5b,
	0xaf, 0x01, 0x00, 0x00,
}
